# tox.ini

[tox]
# Указываем, в каких средах мы хотим проверить наш код.
# py39 = Python 3.9, py310 = Python 3.10, flake8 = среда для линтера
envlist = py39, py310, py311, flake8

# Опция, чтобы tox не требовал файл setup.py (полезно для простых скриптов)
skipsdist = True

# --- Настройка для тестов (pytest) ---
[testenv]
# Зависимости, которые tox установит в чистую среду перед тестами
deps =
    pytest
# Команды, которые tox выполнит
commands =
    pytest -v

# --- Отдельная настройка для линтера (flake8) ---
[testenv:flake8]
# Линтеру не нужен pytest, ему нужен только сам flake8
deps =
    flake8
commands =
    # Проверяем все .py файлы в текущей папке
    flake8 .